spring.application.name=api-gateway

server.port=8090

# =====================
# GATEWAY HTTPS
# =====================

server.ssl.enabled=true
server.ssl.key-alias=remote
server.ssl.key-store-type=PKCS12
server.ssl.key-store=classpath:jobportal-ssl.p12
server.ssl.key-store-password=remote


# =====================
# CORS
# =====================

spring.cloud.gateway.server.webmvc.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:3000,http://localhost:5173
spring.cloud.gateway.server.webmvc.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.server.webmvc.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.server.webmvc.globalcors.cors-configurations.[/**].allowCredentials=true


# =====================
# AUTH SERVICE
# =====================

#spring.cloud.gateway.server.webmvc.routes[0].id=auth-service
#spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:8091
#spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/auth/**


# =====================
# USER SERVICE
# =====================
#
#spring.cloud.gateway.server.webmvc.routes[1].id=user-service
#spring.cloud.gateway.server.webmvc.routes[1].uri=http://localhost:8092
#spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/user/**