spring.application.name=api-gateway
server.port=8090

# =========================
# GATEWAY HTTPS
# =========================
server.ssl.enabled=true
server.ssl.key-alias=remote
server.ssl.key-store-type=PKCS12
server.ssl.key-store=classpath:jobportal-ssl.p12
server.ssl.key-store-password=remote


# =========================
# GATEWAY -> BACKEND HTTPS
# =========================

spring.ssl.bundle.jks.backendtrust.truststore.location=classpath:backend-truststore.p12
spring.ssl.bundle.jks.backendtrust.truststore.password=remote
spring.ssl.bundle.jks.backendtrust.truststore.type=PKCS12

# IMPORTANT for Spring Cloud Gateway 4.1.x
spring.cloud.gateway.mvc.http-client.ssl-bundle=backendtrust

gateway.auth.url=${AUTH_SERVICE_URL:https://localhost:8091}
gateway.user.url=${USER_SERVICE_URL:https://localhost:8092}
gateway.userActivate.url=${USER_ACTIVATION_SERVICE_URL:https://localhost:8094}