spring.application.name=api-gateway

server.port=8090

# Gateway HTTPS
server.ssl.enabled=true
server.ssl.key-alias=remote
server.ssl.key-store-type=PKCS12
server.ssl.key-store=classpath:jobportal-ssl.p12
server.ssl.key-store-password=remote

# Backend certificates trusted by Gateway
spring.cloud.gateway.httpclient.ssl.trusted-x509-certificates=classpath:auth-service.crt,classpath:user-service.crt


spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:3000,http://localhost:5173
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=true

# =====================
# AUTH SERVICE
# =====================
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=https://localhost:8091
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**,/projectLoginpage/**,,/projectModuleDashboard/** 


# =====================
# USER SERVICE
# =====================
spring.cloud.gateway.routes[1].id=user-service
spring.cloud.gateway.routes[1].uri=https://localhost:8092
spring.cloud.gateway.routes[1].predicates[0]=Path=/user/**